// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jrjwniuwwfucyvecqtvj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpyanduaXV3d2Z1Y3l2ZWNxdHZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0MzMwMTksImV4cCI6MjA2MDAwOTAxOX0.Xt0S2U0YOIz12BM8xOimeOiJdSnF_oFb7-UqaloC8uM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);